export const BossDescriptions = {} as const

export const BossImages = {
  AncientContruct: 'AncientContruct.webp',
  BarbedTerror: 'BarbedTerror.webp',
  BlinkThief: 'BlinkThief.webp',
  Brabus: 'Brabus.webp',
  Brudvaak: 'Brudvaak.jpg',
  Canker: 'Canker.webp',
  Claviger: 'Claviger.webp',
  DreamEater: 'DreamEater.webp',
  Dreamer: 'Dreamer.webp',
  EntBoss: 'EntBoss.webp',
  ErforTheJackal: 'ErforTheJackal.jpg',
  Gorefist: 'Gorefist.webp',
  Harsgaard: 'Harsgaard.jpg',
  HarsgaardRootHarbinger: 'HarsgaardRootHarbinger.jpg',
  Ikro: 'Ikro.webp',
  IskalQueen: 'IskalQueen.webp',
  Ixillis: 'Ixillis.webp',
  KinCaller: 'KinCaller.webp',
  Maul: 'Maul.webp',
  Nightmare: 'Nightmare.webp',
  Obryk: 'Obryk.jpg',
  Onslaught: 'Onslaught.webp',
  Raze: 'Raze.webp',
  RiphideLetosArmor: 'RiphideLetosArmor.webp',
  RootHorror: 'RootHorror.webp',
  RootMother: 'RootMother.jpg',
  ScaldAndSear: 'ScaldAndSear.webp',
  Scourge: 'Scourge.webp',
  ShadeAndShatter: 'ShadeAndShatter.webp',
  Shroud: 'Shroud.webp',
  Singe: 'Singe.webp',
  StormCaller: 'StormCaller.webp',
  TheHarrow: 'TheHarrow.webp',
  HoundMaster: 'HoundMaster.webp',
  TheMangler: 'TheMangler.webp',
  TheRavager: 'TheRavager.webp',
  Thrall: 'TheThrall.webp',
  TheUncleanOne: 'TheUncleanOne.webp',
  TianTheAssassin: 'TianTheAssassin.jpg',
  TotemFather: 'TotemFather.webp',
  UndyingKing: 'UndyingKing.webp',
  Warden: 'Warden.webp',
} as const
