export const Descriptions = {
    // Bosses
    AncientContruct: `Located outside of Wud's shop. In order to activate the Ancient Construct you have to acquire the Control Rod by killing Maul with a specific strategy.During the fight break the Houndmaster's "horn", a couple of shots or a shotgun blast will suffice. When it starts to glow, the Control Rod should be visible. Maul will then attack its master.If you die the Houndmaster will not respawn and you will receive the Control Rod when Maul is defeated, provided that the device has been broken before.Return to Wud's shop and place the Control Rod into the chest of the Vyr automaton to activate it. This begins a boss fight against the Ancient Construct. NOTE: You must have Houndmaster and Wud's shop in the same map to be able to activate the Ancient Construct.You cannot keep the Control Rod. It will be removed from your inventory when you re-roll the world.`,
    BarbedTerror: `Barbed Terror is a Boss in Remnant: From the Ashes added with the Swamps Of Corsus DLC.`,
    BlinkThief: `The Boss may not spawn in your playthrough, and you will need to re-roll the campaign to attempt to get it.`,
    Brabus: `Brabus is a Boss in Remnant: From the Ashes. Brabus is a boss that is located in the Earth realm. The Boss may not spawn in your playthrough, and you will need to re-roll the campaign/Adventure Mode to find it.`,
    Brudvaak: `Location: Reisum - The Crimson Hold. Brudvaak, the Rider and Vargr, the Warg is a Boss in Remnant: From the Ashes.`,
    Canker: `Location: Corsus, The Drowned Trench > Mire Hollow. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    Claviger: `Location: Rhom, Loom of the Black Sun > The Spindle. This boss is semi optional, it is one of two options for getting the key to the Undying King. The other option would be The Harrow.`,
    DreamEater: `Location: Corsus, Hall of Whispers > Corrupted Sanctum. This boss may not spawn on your playthrough and you will need to re-roll your Campaign/Adventure Mode to find it. Dream Eater is a Boss in Remnant: From the Ashes added with the Swamps Of Corsus DLC.`,
    Dreamer: `Location: Ward 17. Dreamer is a World Boss in Remnant: From the Ashes. Defeating this boss will immediately trigger the fight against Nightmare.`,
    EntBoss: `Location: Earth, The Choking Hallow. Either this boss, or Singe will spawn in the world.`,
    ErforTheJackal: `Location: Reisum > Wild Reach > Den of the jackal. This boss may not spawn in your playthrough, you will need to re-roll your Campaign/Adventure Mode to find it.`,
    Gorefist: 'Gorefist is a Boss in Remnant: From the Ashes. Bosses are special Enemies that are uniquely named and must be defeated to progress the game, and to acquire special items and gear.',
    Harsgaard: `Location: Ward Prime. This boss is not optional. He is the final boss of the Subject 2923 DLC.`,
    HarsgaardRootHarbinger: `Location: Ward Prime. This boss is not optional. This boss fight will begin as soon as you defeat Harsgaard.`,
    Ikro: `Location: Reisum > Wuthering Keep. This boss may not spawn on your playthrough, you will need to re-roll your Campaign/Adventure Mode to find it.`,
    IskalQueen: `Location: Queen's Temple in Corsus. (Adventure Mode). This boss is optional. Prerequisite: You must gift her the Guardian's Heart during your Campaign. When you approach her, she will talk about how you gave her the Guardian's Heart and will provide you with the Cryptolith Sigil. Used to acquire: - Concentration and Blood Bond Traits. - Labyrinth Set.`,
    Ixillis: `Location: Corsus, The Grotto. This boss is optional if you kill the Undying King instead.`,
    KinCaller: ``,
    Maul: `Location: Rhom, The Burrows >  Stalker's Den. The Boss may not spawn in your playthrough, and you will need to re-roll the campaign/Adventure Mode to find it.`,
    Nightmare: `Location: Ward 17. Appears after defeating the Dreamer.`,
    Obryk: `Location: Reisum > Exiles's Trench. This boss may not spawn on your playthrough, you will need to re-roll your Campaign/Adventure Mode to find it.`,
    Onslaught: `Location: Yaesha, Widow's Pass > Noble's Rest. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    Raze: `Location: Rhom, Lair of the Eyeless. The Boss may not spawn in your playthrough, and you will need to re-roll the campaign/Adventure Mode to find it.`,
    RiphideLetosArmor: `Earth - Leto’s Lab > The Cursed Station. There is a chance that this boss does not spawn in your playthrough. You will need to re-roll your Campaign/Adventure Mode to find it.`,
    RootHorror: `Location: Yaesha - Guardian Shrine requiring Strange Curio which can found at the back of the Stuck Merchant cart. The boss will appear after you unlock the statue that has the Radiant Visage inside. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    RootMother: `The Root Mother is actually not a boss that you fight, rather she is an NPC that you defend for a set amount of time.  After progressing enough through the Earth Realm while in Campaign Mode (Root Mother does not appear in Adventure Mode) you will come across a church with a white fog wall, and a Crystal to rest at.  Upon entering, she gives dialogue options, and ultimately, you must defend her from a Root Ambush.  Upon victory, she will move to Ward 13 where she is used for gaining additional heals, assuming you have the materials.`,
    ScaldAndSear: `Location: Yaesha, Withering Village >  Warden's Pulpit. These Bosses may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find them.`,
    Scourge: `Location: Rhom, The Iron Rift > The Hive. The Boss may not spawn in your playthrough, and you will need to re-roll the Campaign/Adventure Mode to find it.`,
    ShadeAndShatter: `Location: Rhom, The Ardent Temple > Hall of the Faithful. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign or Adventure Mode to find it.`,
    Shroud: `Location: Earth, The Hidden Sanctum >  The Tainted Well. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign or Adventure Mode to find it.`,
    Singe: `Location: Earth, The Ash Yard. Either this boss, or The Ent will spawn in the world.`,
    StormCaller: `Location: Yaesha, Heretic's Nest > Martyr's Garden. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    TheHarrow: `Location: Rhom, The Bunker. This is one of the two possible world boss in Rhom. Defeating him rewards you with the key to the Undying King. The other possible world boss giving you this key is Claviger.`,
    HoundMaster: `Houndmaster is a Merchant that provides Consumables. Location: Rhom. In order to buy the Houndmaster's Jerky, you need to interact with the fire closest to him from the side closest to the door and exhaust his dialog.`,
    TheMangler: `Location: Earth,  The Tangled Pass > The Artery. The Boss may not spawn in your playthrough, and you will need to re-roll the campaign/Adventure Mode to find it.`,
    TheRavager: `Location: Yaesha > The Tempest Court > The Ravager's Haunt. Either this boss, or the Totem Father will spawn in the world.`,
    Thrall: `Location: Corsus, The Capillary > Musk Forge. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    TheUncleanOne: `Location: Corsus, The Shack. This boss is not optional if you choose to complete Corsus.`,
    TianTheAssassin: `Location: Reisum > Valenhaag Mines. This boss may not spawn on your playthrough and you must re-roll your Campaign/Adventure Mode to find it.`,
    TotemFather: `Location: Yaesha - The Tempest Court. Either this boss, or The Ravager will spawn in the world. Switching the totem colors will alter the boss' attack patterns and the minions he summons. Blue: Boss attack pattern will favor ranged and the minions he summons favor melee. Red: Boss attack pattern will favor melee and the minions he summons favor range.`,
    UndyingKing: `Location: Rhom, Undying Throne. You can find the entrance behind the Monolith near the entrance to Rhom (there is a checkpoint that you can teleport to). In order to enter, you'll need the Howling Key that can be obtained by defeating either Claviger or The Harrow.
Encountering the boss is not optional, but fighting him is. The player may choose to comply with the Undying King's request and bring him the Guardian's Heart from Corsus, or instead antagonize the Undying King and fight him. If the player agrees to bring him the Guardian's Heart, he will then open the portal to Corsus.
If you give him the Guardian's Heart he will give you Labyrinth Key and Riven.
The player may agree with the Undying King first, and betray him later, only gaining a slightly quicker access to Corsus.
Note: Obtaining the Labyrinth Key from the Undying King by killing him allows the player to bypass Corsus altogether if the player so chooses.
Note: The Iskal Queen in Corsus also desires the Guardian's Heart, and the player cannot give the item to both NPCs.`,
    Warden: `Location: Yaesha, The Halls of Judgement > The Ring of Trials. The Boss may not spawn in your playthrough, and you will need to re-roll your Campaign/Adventure Mode to find it.`,
    Wolf: `Location: Yaesha > The Tempest Court > The Ravager's Haunt. Either this boss, or the Totem Father will spawn in the world.`,
    // Amulets
    AbrasiveAmulet: `Doubles application of the CORRODED effect. Melee Charge Attacks apply the CORRODED effect.`,
    AmuletOfEpicaricacy: `Increases Mod Power generation by 15%. When attacking an enemy with an active STATUS effect, Mod power generation is increased by an additional 30%.`,
    AmuletOfPerseverance: `Increases earned Experience by 1% when slaying an enemy and will last until the wearer dies, unequips the amulet, or rests at a checkpoint. Stacking up to 50 times.`,
    BlackRose: `The wearer's chest armor set bonus is increased by 1 piece. It will not exceed the 3 piece armor set bonus.`,
    BlessedNecklace: `Receiving a benefit from a Dragon Heart reduces incoming damage by 30% for 10 seconds.`,
    BrutalMark: `After being equipped for 60 seconds, increases all damage by 25% to enemies that have less than 50% Health.`,
    ButchersFetish: `Gain 15% Crit Chance and 25% Crit Damage for 10 seconds after striking an enemy with a Charge Melee Attack.`,
    CharcoalNecklace: `Increase FIRE damage from all sources by 15% and BURNING damage by 50%.`,
    CleansingJewel: `Dragon Heart removes all STATUS effects from all allies. STATUS effect buildup on wearer is reduced by 50%.`,
    DaredeveilsCharm: `Increases Total damage dealt by 30% for each piece of unequipped armor. Damage received is increased by 15%.`,
    Driftstone: `Doubles FROSTBITE application.`,
    GalenicCharm: `Increases Weapon Mod damage by 25%.`,
    GunslingersCharm: `Increases Fire Rate by 15% and Reload Speed by 20%.`,
    HangsmansMemento: `Increase Weakspot damage by an additional 50% for 10 seconds after killing an enemy.`,
    HeartOfDarkness: `Increases Ranged and Melee damage dealt by 20%. Increases damage received by 50% for 30 seconds after using a Dragon Heart.`,
    LetosAmulet: `Reduces Armor Encumbrance by 40% and Stamina cost by 15%.`,
    MendersCharm: `Dragon Hearts heal all allies with 100% base effectiveness. Increases all Healing Effectiveness by 50%.`,
    NightmareSpiral: `Ranged hits steal 6% of base damage dealt as Health. Consumable Healing Effectiveness is reduced by 95%.`,
    OnyxPendulum: `Dealing firearm damage adds stacks which increase the damage of the stowed firearm by 2.5% for 15 seconds. Stacks 10 times.`,
    PocketWatch: `Increases Stamina Regen by 20 per second and reduces Stamina Cost by 20%.`,
    PolishedWhetstone: `When attacking a BLEEDING enemy, Crit Chance is increased by 15% and Crit Damage increased by 35%.`,
    RadioactiveEmber: `Increases RADIATION damage by 15% and converts basic melee weapons from physical to elemental dealing RADIATION damage.`,
    RazorwireNecklace: `Increase BLEEDING damage by 50% and Ranged and Melee damage dealt to enemies with BLEEDING by 15%.`,
    RockOfAnguish: `Gain 10% Movement Speed and 15% Reload Speed for every 25% of Max Health missing.`,
    RustedAmulet: `Reduces Stamina Cost by 80% but increases Armor Encumbrance by 25.`,
    ScavengersBauble: `Increases the amount of Scrap picked up by 50%.`,
    ShatteredVertebrae: `Increase Ranged damage by 10%. When dealing Non-Critical damage with a firearm, Crit Chance is increased by 2% and Crit damage is increased by 5%. When a Critical Hit occurs, Crit Chance and Crit Chance damage are reset.`,
    SoulAnchor: `Increases the duration of summons creatures by 100% and increases wearer's Ranged and Melee damage by 6.25% (max 25%) per summoned minion.`,
    StalkersBrand: `Firearm sound is reduced by 25%. When crouched, increases Movement Speed by 20% and reduces enemy Awareness Range by 15%.`,
    StormAmulet: `Increases SHOCK damage by 15%. Weapon Mods that inflict SHOCK damage deal an additional 10%.`,
    TalismanOfAnimosity: `Increases Weakspot damage by 30%. Weakspot kills increase all damage by 10% for 10 seconds.`,
    TalismanOfPerserverance: `Increases earned Experience by 1% when slaying an enemy and will last until the wearer dies, unequips the amulet, or rests at a checkpoint. Stacking up to 50 times.`,
    TerrorMargin: `Melee hits steal 1.5% of the base damage dealt as Health. For every 25% missing Health, gain an additional 1.5% lifesteal. With full health, gain 20% Melee damage.`,
    TwistedIdol: `Increases Armor Effectiveness by 30% and reduces Encumbrance by 15.`,
    VengeanceIdol: `All damage dealt is increased by 30% when the wearer's Health is below 50%. Includes Summons.`,
    VulcansDetonator: `Increases Explosion Damage by 25%. Explosions apply BURNING status effect.`,
    WhiteRose: `Increases all damage dealt by 25% for each unequipped firearm.`,
    // Rings
    AggressorsBane: `Reduces incoming damage by 15%, but also increases enemy aggression towards the wearer, and increases enemy Awareness Range by 200%.`,
    AkariWarBand: `Perfect Dodging enemy attacks increases Crit Chance by 15% and Crit damage by 15% for 20 seconds.`,
    AlchemistJewel: `Increase Armor Effectiveness by 50% and Armor Encumbrance by 25.`,
    AmberMoonstone: `When the wearer's Health drops below 25% they gain 25% damage reduction and immunity to STATUS effects.`,
    BackbreakerRing: `Increase Melee Backstab dmg by 30%.`,
    BandOfAccord: `Ammo acquired on pickup is increased by 25% per ally also wearing this ring and is shared with other allies.`,
    BandOfCastor: `Increases Melee Speed by 10%, but reduces Fire Rate by 15%. While wearing BAND OF POLLUX, Melee damage is increased by 10%, Evade Speed is increased by 15% and Encumbrance is reduced by 25.`,
    BandOfDiscord: `Reduces Consumable Use Speed by 15%. Dragon Hearts heal the wearer with 125 Health over 30 seconds.`,
    BandOfPollux: `Increases Melee damage by 15%, but reduces Ranged damage by 15%. While wearing BAND OF CASTOR, Melee Damage is increased by 10%, Evade Speed is increased by 15% Encumbrance is reduced by 25.`,
    BandOfStrength: `Melee Charge Attacks increase Melee damage by 5% for 10 seconds. Stacks 4 times.`,
    BlackCatBand: `When taking fatal damage, instead of dying, the wearer's Health will drop to 1, and Movement Speed will increase by 25% for 10 seconds. 1 minute cooldown.`,
    BloodFontRing: `Increases Health regenerates by 0.334 per second and increases all Healing Effectiveness by 15%.`,
    BloodlettersInsignia: `BLEEDING effects applied by the wearer steal 10% of the damage dealt and return it to the wearer as Health.`,
    BraidedThorns: `Increase Crit Chance by 10%. Gain an additional 10% for 10 seconds after slaying an enemy.`,
    BrightSteelRing: `Gives wearer the fastest evade roll regardless of their Armor Encumbrance.`,
    BurdenOfTheDevoted: `All damage dealt by wearer is reduced by 15%. 50% of self healing applies to allies.`,
    BurdenOfTheFollower: `Reduces Fire Rate by 35%. Increases Mod Power generation by 100%.`,
    BurdenOfTheGambler: `Disables Weakspot damage bonus. Increases Crit Chance by 15% and Crit Damage by 25%.`,
    BurdenOfTheReckless: `Disables healing from Dragon hearts. Perfect dodging enemy attacks will regenerate 5% of the wearer's Max Health per second over 5 seconds.`,
    BurdenOfTheWarlord: `Reduces effective range of all firearms by 50%. Increases all damage dealt by 15%.`,
    CelerityStone: `Increases Consumable Use Speed by 40%. After using a Consumable, increases Reload Speed by 20% and Weapon Swap Speed by 25% for 15s.`,
    CompulsionLoop: `Increase Movement Speed by 20%, Fire Rate by 15%, and Melee Speed by 10% for 7 seconds after slaying an enemy.`,
    DeceiversBand: `Increases Evade Speed by 25% and Movement Speed by 15% for 10 seconds after performing a slide.`,
    DevouringLoop: `Critical Hits have a 5% chance to deal 4x damage.`,
    EmpoweringLoop: `Increases Ranged damage by 25%, but decrease Fire rate by 10%.`,
    EvokersSeal: `Refunds 15% Mod Power on use.`,
    EzlansBand: `Increases Health by 25 and Health regeneration by 0.238 per second.`,
    FiveFingeredRing: `Increases Unarmed Melee damage by 50%, Crit damage by 25%, and Crit Chance by 20%.`,
    GiftOfTheIskal: `Mod power is generated slowly over time, but reduces the wearer's Healing Effectiveness by 15%.`,
    GravityStone: `Increases damage by 20% when there are at least 2 enemies within 10 meters of the wearer.`,
    GrimCoil: `Reloading a weapon after dealing at least 40% of the base damage from a single magazine increases damage by 7% for 20 seconds. Stacks 3 times.`,
    GuardiansRing: `Reduce incoming melee damage by 20%.`,
    GunslingersRing: `Increases Firearm Swap Speed by 50% and Fire Rate by 10%.`,
    GunslignersRing: `Increases Firearm Swap Speed by 50% and Fire Rate by 10%.`,
    HeartOfTheWolf: `Increases Max Stamina by 25 and Movement Speed by 10%.`,
    HeartSeeker: `Provides a 100% Crit Chance against non-aggressive enemies and increases Crit Damage by 20%.`,
    HerosRing: `Increases Movement Speed by 25% while sprinting towards a wounded teammate. Revive Speed is increased by 100% and the wearer cannot by staggered while reviving.`,
    HuntersBand: `Increases Ranged damage by 10% and Weakspot damage by 20%.`,
    HuntersHalo: `Increase the effective Range of all firearms by 6m.`,
    IskalHunterBand: `Reduces Spread by 40%.`,
    JewelOfTheBlackSun: `Increases Ranged damage by 7% for 20 seconds after a Ranged kill. Stacks 3 times.`,
    JuggernautBand: `After sprinting for 2 seconds, incoming damage is reduced by 10%, Movement Speed is increased by 15%, stagger level is reduced by 1, and the wearer will perform the heaviest evade.`,
    KeepersRing: `Increases resistance to all ELEMENTAL damage by 20.`,
    LeechEmber: `Melee hits steal 5% of the base damage dealt as Health from enemies.`,
    LoopOfProsperity: `Metal materials acquired on pickup are doubled.`,
    MothersRing: `Reduces incoming Ranged Damage by 20%.`,
    PearlOfLuminescence: `Wearer has a 70% chance to double the amount of Lumenite Crystal acquired on pickup when killing Elite enemies.`,
    PillarOfStone: `Reduces Recoil by 30% and Weapon Sway by 60%. Standing Aim Movement Speed is increased by 50%.`,
    PrismaticDiamondRing: `Increases ELEMENTAL damage by 10%.`,
    ProvisionerRing: `Firearms reload over time while stowed.`,
    RazorStone: `Melee Charge Attacks apply the BLEEDING effect, dealing 600 over 20 seconds.`,
    RestrictionCord: `Restricts the wearer from Healing above 50% of their Max Health and reduces incoming damage by 15%.`,
    RingOfElusion: `Perfect Dodging enemy attacks refunds 50 Stamina and reduces Stamina Cost by 100% for 10 seconds.`,
    RingOfEvasion: `Moderately increases Evade Window and increase Evade Speed by 10%.`,
    RingOfFlawlessBeauty: `Ranged Weakspot damage is increased by 40%. Ranged damage is reduced by 20% when failing to shoot a weakspot.`,
    RingOfHonor: `Increases Health by 10, Stamina by 10, and reduces Armor Encumbrance by 10.`,
    RingOfShadows: `Reduces enemy Awareness Range by 25%. Increases damage against non-aggressive enemies by 15%.`,
    RingOfSupremacy: `Increases all damage dealt by 20% after the wearer's health has been full for at least 10 seconds.`,
    RingOfSynergy: `Increase Teamwork effect by 10% and Revival speed by 11% per ally also wearing this ring.`,
    RingOfTheAdmiral: `Damage received is increased by 300%. All damage dealt is increased by 15%.`,
    RingOfTheMantis: `Increases Fire Rate by 15% and Crit damage by 20% when the wearer stops moving for at least 1 seconds.`,
    RingOfThePunisher: `Increases damage to enemies affected by STATUS effects. Each unique STATUS applied increases all damage by 5%.`,
    RingOfTheUnclean: `Unarmed Melee attacks deal 2x damage. Heavy Flops deal 4x damage.`,
    RootCirclet: `Increases Melee Speed by 15%.`,
    SageStone: `Increases earned Experience by 30%.`,
    ScavengersRing: `Collecting Scrap, Iron, and Ammo pickups regenerates 3% of Max Health and increases Ranged and Melee damage by 10% for 30 seconds.`,
    SerpentsFang: `Increased Charged Melee Damage by 20%.`,
    SoulEmber: `Summon Health is reduced by 60%. On death they'll explode dealing 150 plus 15 damage per weapon level within 4 meters. Summons that explode normally will deal 25% bonus damage. Excess summons will explode when another summon is used.`,
    SoulLink: `Summons will steal 5% of the damage dealt and return it to the wearer as Health.`,
    SpiritStone: `Increases Mod Power generation by 25% and Weapon Mod damage by 10%.`,
    StockpileCirclet: `Increases Max Ammo reserves for all firearms by 50%.`,
    StoneOfBalance: `Increases Ranged and Melee damage by 12%.`,
    SwashbucklersSignet: `Build one buff stack every 20 seconds up to a max of 3 stacks. Melee Charge Attacks consume one stack and replenish 15% of the wearer's ammo capacity for both firearms.`,
    VanguardRing: `Melee Charge attacks reduce incoming and outgoing damage by 4% and increase enemy aggression towards the wearer for 15 seconds. Stacks 5 times.`,
    VolatileGem: `Dragon Hearts explode dealing 600 damage plus 10% per gear score and inflict 100% extra stagger damage within 5 meters.`,
    // keyitems/
    AcesCoin: `Can be found randomly anywhere on Earth. You can give this item to Ace, and she will reward you with Magnum Revolver.`,
    AcidCleanedKey: `Can be acquired by wearing the Rusted Amulet and crouching on one of the acid pools located in the Fetid Pool in Corsus. The Rusted Amulet will be gone and you will acquire the Acid Cleaned key.`,
    ArmorVaultKey: ``,
    ControlRod: `Drop by Maul. Used to activate the Ancient Construct outside of Wud's shop in Rhom. Break the Houndmaster's "horn", a couple of shots or a shotgun blast will do the trick, and when it starts to glow the control rod should become visible. Maul will then attack it's master. If you die the Houndmaster will not respawn and you will receive the Control Rod when Maul is defeated provided that the device has been broken before.`,
    CreepersEye: `Can be found inside the cage in Watcher's Hollow - Reisum. You'll need the Servant Cage Key to open the cage. The item is not found as a lootable object in the cage. You will need to kill the slaves to get this item. You don't have to kill at random. Look at their eyes and kill the one with false green eye.`,
    CryptolithSigil: `Prerequisite to get this item is to give the Guardian's Heart to the Iskal Queen during the campaign. Can be obtained through Adventure Mode by finding the Iskal Queen and speaking with her in the Queen's Temple on Corsus. She is not a guaranteed spawn.`,
    DATLAKey: `Acquired from Commander Ford after turning on the reactor at Ward 13. This key can power the crystal terminal in Ward 13.`,
    FoundersKey: `This key unlocks a computer connected to a mirror on the lower levels of Ward 13. Given to you after freeing Founder Ford at Yaesha > Founder's Prison.`,
    Fuse: `Can be used to fill the empty fuse slot located on Ward 13. Can be found on one of the rooms located in the basement of Ward 13.`,
    GuardianHeart: `Kill Ixillis in Corsus. Give to the Undying King or the Iskal Queen to complete their quests.`,
    HomesteadKey: `Can be found in Ward Prime in Dr. Enji Sato and Dr. Sebastian Weisskoof's office, as long as Homestead has spawned on Earth's Rural areas. You will have to go back to the Homestead waypoint and exit the shack. Go inside the House and you will see two shelves. Destroy them to reveal a secret path. Go down and use the key to unlock the door and you will find the Vanguard Ring.`,
    HowlingKey: `Can be obtained by defeating Claviger. Can be obtained by defeating The Harrow. Can be used to gain access to the altar of the Sun Gate leading to the Undying King.`,
    HuntersKey: `Can be found at Earth > Hidden Grotto on the random event Hunter's Hideout. It's provided by the Hunter that sits next to the checkpoint. Can be used to open the Hunter's Safehouse to get the Hunting Pistol.`,
    IskalVial: `Can be acquired by talking to the Iskal Queen with the PARASITE effect from Iskal Infector and telling her you want to help the Iskal. In order to get the Iskal Vial, you must have the Graveyard Elf and the Iskal Queen in the same Corsus map. (Adventure mode)`,
    JanitorsWatch: `Can be randomly found in Reisum > Drolniir Woods.`,
    LabKeycard: ``,
    LabyrinthKey: `Can be used to access the Labyrinth. Given to the player by the Undying King in exchange for the Guardian's Heart. Given as a reward upon killing the Undying King.`,
    LastWillKey: `Can be used to open a locked door where Chicago Typewriter can be found. Can be obtained by successfully passing the random event A Tale of Two Liz's.`,
    ManyFacesKey: ``,
    MonkeyKey: `Found on the random event Supply Run in Sorrow's Field dungeon on Earth. Can be used to access a room where Assault Rifle can be found in Sorrow's Field dungeon on Earth.`,
    OpalescentShell: `Can be acquired from the Mudling Queen Beetle from the Abandoned Throne event in Corsus. Mudling Queen Beetle appears when you kill the other beetles around the the Abandoned Throne.`,
    PackmastersTusk: `Can be acquired by defeating the Pack Master. Can be delivered to Sebum as part of the Warlord's Set armor quest line. It will only drop if Sebum is in that map.`,
    ServantCageKey: `Can be found at the end of Watcher's Hollow > Reisum. Can be used to open the cage at Watcher's Hollow where the Emin servants are located. You can kill the Emin with the false green eye to acquire the Creeper's Peeper required for the Creeper's Peepers Event.`,
    SimpleKey: ``,
    StrangeCoin: `Can be found randomly anywhere on Earth. You can give this item to Ace, and she will reward you with Magnum Revolver.`,
    TarnishedRing: `Can be found at a random location at Earth. Can be given to Reggie to receive the Scavenger Trait.`,
    ReggiesRing: `Can be found at a random location at Earth. Can be given to Reggie to receive the Scavenger Trait.`,
    VyrControlDevice: ``,
    Ward13Keycard: `Can be found at Earth on top of a table at Founder's Hideout. Allows the player to unlock the doors in Ward 13.`,
    WardPrimeFuse: `Can be found at Ward Prime inside the Laboratory area, on the obstructed door located on the left side. Can be used to restore the power to the main level of Ward Prime.`,
    WardPrimeKeyCard: `Can be found inside the Medical Storage area of Ward Prime. You'll need to restore the energy from the reactor room and use the computer to unlock the door.`,
    WarPrimMaintenanceKey: `Can be found in the Medical Area located at Ward Prime. You'll need to vault over a broken window and destroy a bookshelf to acquire it.`,
    // Crafting Materials
    AncientCore: ``,
    BarbedSinew: ``,
    BlackTear: ``,
    BlazingHeart: ``,
    BlinkSpearShard: ``,
    ButchersHeart: ``,
    ColdCell: ``,
    CrystallinePlasma: ``,
    DisplacementCrystal: ``,
    DragonLinks: ``,
    DreamersMana: ``,
    FleshBarb: ``,
    ForgedIron: ``,
    GalvanizedIron: ``,
    GlacialScepter: ``,
    GlowingFragment: ``,
    GuardiansTentacler: ``,
    HammerheadsOre: ``,
    HardenedCarapace: ``,
    HardenedIron: ``,
    HiveStone: ``,
    HollowSeed: ``,
    HoundChoker: ``,
    Iron: ``,
    IskalHusk: ``,
    JackalsIvory: ``,
    KinCallerBell: ``,
    LumeniteCrystal: ``,
    LuminousGland: ``,
    ObryksBracelet: ``,
    RadioactiveSkull: ``,
    RootNeoplasm: ``,
    SentinelShard: ``,
    Shadewood: ``,
    ShrapnelShard: ``,
    SilverFragment: ``,
    Simulacrum: `Can be found anywhere, with a max of 1 per world. Can be used to upgrade Weapons and Armor to its max level. Can be used to upgrade the Dragon Heart.`,
    SlimeVessel: ``,
    SporeGland: ``,
    StalkersClaw: ``,
    SteelOfAgony: ``,
    StoneOfTheGuardian: ``,
    SwarmTusk: ``,
    TempestHeartstring: ``,
    TentaclePod: ``,
    ThermalGeode: ``,
    TheUndyingHeart: ``,
    TotemAntler: ``,
    TwistedHeart: ``,
    VoidSliver: ``,
    ZephyrConduit: ``,
    // Consumables
    Adrenaline: `Increases Movement Speed by 15%, standing Aim Movement Speed by 25%, and Melee Speed by 10%. Lasts 30 seconds.`,
    AmmoBoxGuide64Px: `Replenishes all ammo.`,
    AmmoBox: `Replenishes all ammo.`,
    AntiSerum: `Neutralizes PARASITE effect.`,
    Bandage: `Stops the BLEEDING effect.`,
    BeetleExtract: `Increases Stamina Regen by 20 per second. Lasts 60 minutes and will stay in effect after death.`,
    Bloodwort: `Regenerates 1.7 Health per second for 30 seconds.`,
    DivineNectar: `Increases armor effectiveness by 10%. Lasts 60 minutes and will stay in effect after death.`,
    DragonHeart: `Resurrects a fallen ally and instantly replenishes one's health.`,
    ElixirOfEnlightenment: `Increases earned Experience by 25%. Lasts 2 hours and will stay in effect after death.`,
    EtherealOrb: `Removes OVERLOADED effect and increases SHOCK resistance by 30%. Lasts 10 minutes.`,
    FrenzyDust: `Increases Fire Rate by 15% and Reload Speed by 20% for all heroes that step into the dust cloud. Lasts 30 seconds.`,
    GoldenPlum: `Regenerates 0.2 health per second. Lasts 60 minutes and will stay in effect after death.`,
    Greenleaf: `Removes CORRODED effect and increases CORROSIVE resistance by 30%. Lasts 10 minutes.`,
    HandgunAmmo: `Ammo that is used for Hand Gun Firearms.`,
    HeavyWaterElixir: `Removes the IRRADIATED effect and increases RADIATION Resistance by 30%. Lasts 10 minutes.`,
    HoundMastersJerky: `Increases Crit damage by 15%. Lasts 60 minutes and will stay in effect after death.`,
    Hydrocoolant: `Extinguishes BURNING effect and increase FIRE resistance by 30%. Lasts 10 minutes.`,
    Icefruit: `Increase Crit Chance by 5%. Lasts 60 minutes, persists after death.`,
    LiquidEscape: `When consumed, the hero will be returned to the last activated checkpoint.`,
    LonggunAmmo: `Ammo that is used for Long Gun Firearms.`,
    MastersJerky: `Increases Crit damage by 15%. Lasts 60 minutes and will stay in effect after death.`,
    MudtoothsStew: `Increases Stamina by 25. Lasts 60 minutes and will stay in effect after death.`,
    MudtoothsTonic: `Increases Max Health by 25. Lasts 60 minutes and will stay in effect after death.`,
    OilskinBalm: `Removes INFECTED effect and increases ROT Resistance by 30%. Lasts 10 minutes.`,
    OilskinTonic: `Removes INFECTED effect and increases ROT Resistance by 30%. Lasts 10 minutes.`,
    OrbOfUndoing: `Resets Trait Points.`,
    PristineEssence: `Increases resistance to all ELEMENTAL damage by 15 and reduces STATUS effect buildup by 50%. Lasts 3 minutes`,
    Spiceroot: `Removes FROZEN effect and increases FROST resistance by 30%. Lasts 10 minutes.`,
    TraitBook: `Grants a hero 1 Trait Point upon acquiring one.`,
    TomeOfWisdom: `Grants a hero 1 Trait Point upon acquiring one.`,
    // SideQuests
    ArmorVault: ``,
    Flautist: ``,
    HuntersHideout: ``,
    Monolith: ``,
    RootCultist: ``,
    Settlement: ``,
    StuckMerchant: ``,
    WailingWood: ``,
    TheCleanRoom: ``,
    TheLostGantry: ``,
    MudTooth: ``,
    RootShrine: ``,
    // Locations
    Corsus: ``,
    Earth: ``,
    Reisum: ``,
    Rhom: ``,
    TheLabyrinth: ``,
    Ward13: ``,
    WardPrime: ``,
    Yaesha: ``,
    Fairview: ``,
    Westcourt: ``,
    TheEasternWind: ``,
    TheScouringWaste: ``,
    TheVerdantStrand: ``,
    TheFetidGlade: ``,
    TheScaldingGlade: ``,
    TheMistFen: ``,
};
